version: "3.9"
services:
  web:
    build:
      context: ../..
      dockerfile: infra/docker/web.Dockerfile
    ports: ["5173:5173"]
    depends_on: [api]
  api:
    build:
      context: ../..
      dockerfile: infra/docker/api-spring.Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: default
    ports: ["8080:8080"]
    depends_on: [db, redis, rabbitmq, minio]
  worker-java:
    build:
      context: ../..
      dockerfile: infra/docker/worker-java.Dockerfile
    depends_on: [rabbitmq]
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oj
    ports: ["5432:5432"]
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
  rabbitmq:
    image: rabbitmq:3-management
    ports: ["5672:5672", "15672:15672"]
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports: ["9000:9000", "9001:9001"]
